import os
import shutil

def generate_markdown_report(title, filename, score, image_path, synthesis, output_path):
    """
    Generates a Markdown report for a single paper based on the new user template.
    Note: 'synthesis' now contains the full structured report body (Sections 1-4).
    The image path needs to be injected into Section 3.
    """
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    relative_image_path = os.path.relpath(image_path, os.path.dirname(output_path))
    
    # Inject the image into the synthesis text
    # The synthesis text expects a place for the image in Section 3.
    # We will prepend the Title and handle the image insertion.
    
    # Strategy: 
    # The 'synthesis' string from GLM contains Sections 1, 2, 3, 4.
    # We will inject the image markdown right after "## 3. 核心架构与方法解析"
    
    if "## 3. 核心架构与方法解析" in synthesis:
        # Inject image
        image_markdown = f"\n![Model Architecture]({relative_image_path})\n*(注：架构图由系统物理裁剪自动提取)*\n"
        synthesis = synthesis.replace("## 3. 核心架构与方法解析", f"## 3. 核心架构与方法解析{image_markdown}")
    else:
        # Fallback if section header is missing
        synthesis = f"![Model Architecture]({relative_image_path})\n\n{synthesis}"

    markdown_content = f"""# {title}
    
{synthesis}

---
*Generated by GLM Dual-Brain Agent*
"""
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(markdown_content)
    
    print(f"Report generated: {output_path}")

def cleanup_temp_files(image_path):
    """
    Removes the temporary image file. 
    Use this if we truly want to be 'stateless' and maybe embed image or just discard it.
    But based on "relative path" requirement, we probably shouldn't delete the final image 
    unless the report is self-contained (base64).
    
    Let's assume we DON'T delete the final image for now, but we would delete any other temp files.
    Since we only generate one image per paper (the crop), maybe we keep it.
    
    If the user insists on "Stateless Cleanup", maybe they mean cleanup *after* the session or just intermediate files.
    I will leave this function available but maybe not call it on the *result* image.
    """
    if os.path.exists(image_path):
        os.remove(image_path)
        print(f"Deleted temp file: {image_path}")
